# docker-compose.yml
version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
  timescale:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: iot_timescale
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"